# Generated by Django 5.2.5 on 2025-09-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=100)),
                ('no_of_units', models.IntegerField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=100)),
                ('course_n', models.CharField(max_length=100)),
                ('date_enroll', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('student_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parrent_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_contact', models.IntegerField(max_length=100)),
                ('father_contact', models.IntegerField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=100)),
                ('dop', models.DateTimeField()),
                ('pay_method', models.CharField(max_length=100)),
                ('pay_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.IntegerField(max_length=100)),
                ('dob', models.DateTimeField()),
            ],
        ),
    ]
